title:             5T4RB0Y
email:             sssurajsuraj@gmail.com
description:       The legend of J
author:            J
url:               "localhost:4000"
#url:               "https://5t4rb0y.github.io/"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
